import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Database,Activity,ScanLine,Radio,Mic,Video,Image,FolderOpen,Settings,User,RotateCw,ZoomIn,ZoomOut,Layers,RefreshCw,Play,Star} from 'lucide-react';
import './style.css';


const waveTypes=[['sine','Senoidal'],['square','Quadrada'],['triangle','Triangular'],['sawtooth','Serra']];
function noise(ctx,type){const b=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){const w=Math.random()*2-1;if(type==='brown'){last=(last+.02*w)/1.02;d[i]=last*3.5}else d[i]=w}return b}
function Engine({on,gens,master,white,brown,pink}){const ctx=useRef(),nodes=useRef([]);useEffect(()=>{const stop=()=>{nodes.current.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}});nodes.current=[]};stop();if(!on)return;const A=window.AudioContext||window.webkitAudioContext;ctx.current??=new A();const ac=ctx.current;ac.resume();gens.filter(g=>g.enabled).forEach(g=>{const o=ac.createOscillator(),v=ac.createGain();o.type=g.wave;o.frequency.value=g.freq;v.gain.value=(master/100)*(g.volume/100)*.18;o.connect(v).connect(ac.destination);o.start();nodes.current.push(o,v)});[['white',white],['white',pink],['brown',brown]].forEach(([t,n])=>{if(!n)return;const s=ac.createBufferSource(),v=ac.createGain();s.buffer=noise(ac,t);s.loop=true;v.gain.value=n/100*.1;s.connect(v).connect(ac.destination);s.start();nodes.current.push(s,v)});return stop},[on,gens,master,white,brown,pink]);return null}

const menu=[[Home,'Início'],[Database,'Programas de Tratamento'],[Activity,'Leitura / Bioimpedância'],[ScanLine,'Órgãos e Sistemas'],[Radio,'Frequência Livre'],[Mic,'Voz'],[Video,'Vídeo'],[Image,'Foto'],[FolderOpen,'Arquivos'],[Settings,'Configurações']];
const programs=['Função da tireoide','Hipotireoidismo','Hipertireoidismo','Tireoidite','Doença de Graves','Bócio','Nódulos tireoidianos','Câncer de tireoide','Paratireoide','Equilíbrio hormonal'];
function App(){
 const [sex,setSex]=useState('Masculino'),[target,setTarget]=useState({name:'Joelho',top:72,left:50}),[fieldOn,setFieldOn]=useState(true),[layers,setLayers]=useState({Órgão:true,Sistema:true,Esqueleto:false,Vasos:false,Nervos:false,Linfático:false,Muscular:false}),[focusOpen,setFocusOpen]=useState(true),[focusRot,setFocusRot]=useState(0),[focusZoom,setFocusZoom]=useState(1),[on,setOn]=useState(false),[elapsed,setElapsed]=useState(0),[repeat,setRepeat]=useState(1),[infinite,setInfinite]=useState(false),[a,setA]=useState({enabled:true,freq:432,wave:'sine',volume:70,dwell:60,duty:50,offset:0}),[b,setB]=useState({enabled:true,freq:528,wave:'sine',volume:55,dwell:60,duty:50,offset:0}),[selectedProgram,setSelectedProgram]=useState('Equilíbrio hormonal'),[programStep,setProgramStep]=useState(0),[programQuery,setProgramQuery]=useState(''),[master,setMaster]=useState(70),[white,setWhite]=useState(30),[pink,setPink]=useState(25),[brown,setBrown]=useState(20); const sequences={'Função da tireoide':[432,528,741.85],'Hipotireoidismo':[125,432,528],'Hipertireoidismo':[174,285,528],'Tireoidite':[285,432,741],'Doença de Graves':[174,528,963],'Bócio':[125,285,528],'Nódulos tireoidianos':[174,432,741],'Câncer de tireoide':[285,528,963],'Paratireoide':[432,741,963],'Equilíbrio hormonal':[432,528,963]}; const sequence=sequences[selectedProgram]||[432],duration=1800,stepDuration=Math.floor(duration/sequence.length),gens=useMemo(()=>[a,b],[a,b]); useEffect(()=>{setProgramStep(Math.min(sequence.length-1,Math.floor(elapsed/stepDuration)));setA(x=>({...x,freq:sequence[Math.min(sequence.length-1,Math.floor(elapsed/stepDuration))]}))},[elapsed,selectedProgram]); useEffect(()=>{if(!on)return;const id=setInterval(()=>setElapsed(t=>{if(t<duration)return t+1;if(infinite||repeat>1){if(!infinite)setRepeat(r=>Math.max(1,r-1));return 0}setOn(false);return duration}),1000);return()=>clearInterval(id)},[on,infinite,repeat]);
 return <main className="app"><Engine on={on} gens={gens} master={master} white={white} pink={pink} brown={brown}/>
  <header><div className="brand"><b>⚛</b><strong>Quantum <span>VibraSync</span> One</strong></div><div className="top"><i>● Conectado</i><b>▣ Banco de Programas<br/><span>90.893</span></b><User/><Settings/></div></header>
  <div className="workspace">
   <aside>{menu.map(([I,t],i)=><button key={t} className={i===3?'active':''}><I/>{t}</button>)}</aside>
   <section className="content">
    <section className="atlas panel">
      <div className="atlas-title"><h1>Atlas de Tratamento</h1><p>Atlas anatômico sincronizado com a frequência em execução</p></div>
      <div className="sex"><button className={sex==='Masculino'?'on':''} onClick={()=>setSex('Masculino')}>Masculino</button><button className={sex==='Feminino'?'on':''} onClick={()=>setSex('Feminino')}>Feminino</button></div>
      <div className="bodies">
       <div className="body male"><div className="head"/><div className="torso"/><div className="limbs"/>{layers['Órgão']&&<i className="layer organs">●</i>}{layers.Sistema&&<i className="layer endocrine">•••</i>}{layers.Esqueleto&&<i className="layer skeletal">⋮</i>}{layers.Vasos&&<i className="layer vascular">╱╲</i>}{layers.Nervos&&<i className="layer nervous">│</i>}{layers.Linfático&&<i className="layer lymphatic">✦</i>}{layers.Muscular&&<i className="layer muscular">≋</i>}<span>Masculino</span></div>
       <div className="body female"><div className="head"/><div className="torso"/><div className="limbs"/>{layers['Órgão']&&<i className="layer organs">●</i>}{layers.Sistema&&<i className="layer endocrine">•••</i>}{layers.Esqueleto&&<i className="layer skeletal">⋮</i>}{layers.Vasos&&<i className="layer vascular">╱╲</i>}{layers.Nervos&&<i className="layer nervous">│</i>}{layers.Linfático&&<i className="layer lymphatic">✦</i>}{layers.Muscular&&<i className="layer muscular">≋</i>}<span>Feminino</span></div>
       <button className={`body-hit male-hit ${sex==='Masculino'?'selected':''}`} onClick={()=>setSex('Masculino')} aria-label="Selecionar Atlas masculino"/><button className={`body-hit female-hit ${sex==='Feminino'?'selected':''}`} onClick={()=>setSex('Feminino')} aria-label="Selecionar Atlas feminino"/><div className={`target-anchor ${sex==='Feminino'?'female-target':'male-target'}`} style={{top:target.top+'%',left:target.left+'%'}}><div className="target-glow"/>{fieldOn&&<><div className="ring r1"/><div className="ring r2"/></>}</div>{focusOpen&&<div className="focus3d"><small>ESTRUTURA 3D</small><b>{target.name}</b><div className="focus-model" style={{transform:`scale(${focusZoom}) rotateY(${focusRot}deg)`}}>◉<i/></div><nav><button onClick={()=>setFocusRot(r=>r-20)}>↶</button><button onClick={()=>setFocusRot(r=>r+20)}>↷</button><button onClick={()=>setFocusZoom(z=>Math.min(1.5,z+.1))}>＋</button><button onClick={()=>setFocusZoom(z=>Math.max(.7,z-.1))}>−</button><button onClick={()=>{setFocusRot(0);setFocusZoom(1)}}>↺</button></nav></div>}<div className="atlas-state"><b>Alvo ativo: {target.name}</b><button onClick={()=>setFocusOpen(v=>!v)}>{focusOpen?"Ocultar 3D":"Mostrar 3D"}</button><button onClick={()=>setFieldOn(v=>!v)}>{fieldOn?'Campo Quântico ON':'Campo Quântico OFF'}</button></div>
      </div>
      <div className="tools">{[[RotateCw,'Girar'],[ZoomIn,'Aproximar'],[ZoomOut,'Afastar'],[Layers,'Isolar órgão'],[Layers,'Visão interna'],[RefreshCw,'Restaurar']].map(([I,t])=><button key={t}><I/>{t}</button>)}</div>
      <div className="target-demo"><button onClick={()=>setTarget({name:'Cérebro',top:18,left:50})}>Cérebro</button><button onClick={()=>setTarget({name:'Tireoide',top:29,left:50})}>Tireoide</button><button onClick={()=>setTarget({name:'Coração',top:40,left:50})}>Coração</button><button onClick={()=>setTarget({name:'Joelho',top:72,left:50})}>Joelho</button></div><nav className="layers">{['Órgão','Sistema','Esqueleto','Vasos','Nervos','Linfático','Muscular'].map(x=><button key={x} className={layers[x]?'on':''} onClick={()=>setLayers(v=>({...v,[x]:!v[x]}))}>{x}</button>)}</nav>
    </section>
    <section className="related panel"><h3>Programas Relacionados <b>{programs.filter(x=>x.toLowerCase().includes(programQuery.toLowerCase())).length}</b></h3><div className="program-search"><input value={programQuery} onChange={e=>setProgramQuery(e.target.value)} placeholder="Buscar programa"/><button onClick={()=>setProgramQuery('')}>×</button></div>{programs.filter(x=>x.toLowerCase().includes(programQuery.toLowerCase())).map(x=><div key={x} className={selectedProgram===x?'program-selected':''}><span>• {x}</span><button onClick={()=>{setSelectedProgram(x);setElapsed(0);setProgramStep(0);setOn(false)}}><Play/></button><Star/></div>)}</section>
    <section className="reading panel"><h3>Leitura / Bioimpedância</h3><div className="mini-body">♙</div><b>Status</b><p>Aguardando leitura</p><button className="start">▥ Iniciar Leitura</button><div className="checks">✓ Eletrodos conectados<br/>✓ Sinal estável<br/>✓ Calibração OK<br/>✓ Pronto para leitura</div></section>
    <section className="player panel"><h3>Player de Frequência</h3><div className="wave">∿∿∿∿∿</div><b>{selectedProgram}</b><div className="sequence-info"><span>Etapa {programStep+1} de {sequence.length}</span><span>Atual: {sequence[programStep]} Hz</span><span>Próxima: {sequence[programStep+1]??'Fim'}</span></div><input className="timeline" type="range" min="0" max={duration} value={elapsed} onChange={e=>setElapsed(+e.target.value)}/><div className="transport"><button onClick={()=>setElapsed(0)}>◀</button><button onClick={()=>{setOn(false);setElapsed(0)}}>■</button><button onClick={()=>setOn(v=>!v)}>{on?'Ⅱ':'▶'}</button><button onClick={()=>setElapsed(t=>Math.min(duration,t+10))}>▶</button><button onClick={()=>setInfinite(v=>!v)}>{infinite?'∞':'↻'}</button></div><div className="repeat-box"><label>Repetir <select value={repeat} disabled={infinite} onChange={e=>setRepeat(+e.target.value)}>{[1,2,3,4,5,10].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><button onClick={()=>setInfinite(v=>!v)} className={infinite?'on':''}>∞ contínuo</button></div></section>
    <section className="generators panel">{[['Gerador A',a,setA],['Gerador B',b,setB]].map(([n,g,set])=><div key={n}><h3>{n}</h3><label><input type="checkbox" checked={g.enabled} onChange={e=>set({...g,enabled:e.target.checked})}/> Ativo</label><label>Frequência <input type="number" value={g.freq} onChange={e=>set({...g,freq:+e.target.value||1})}/> Hz</label><label>Volume <input type="range" value={g.volume} onChange={e=>set({...g,volume:+e.target.value})}/> {g.volume}%</label><label>Onda <select value={g.wave} onChange={e=>set({...g,wave:e.target.value})}>{waveTypes.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Dwell <input type="number" value={g.dwell} onChange={e=>set({...g,dwell:+e.target.value||1})}/></label><label>Duty <input type="number" value={g.duty} onChange={e=>set({...g,duty:+e.target.value||50})}/></label><label>Offset <input type="number" value={g.offset} onChange={e=>set({...g,offset:+e.target.value||0})}/></label></div>)}</section>
    <section className="waves panel"><h3>Tipo de Onda</h3><div>{['∿ Senoidal','▱ Quadrada','△ Triangular','⌁ Serra','⁙ Ruído Branco','≋ Ruído Rosa','≋ Ruído Marrom','⚙ Personalizada'].map(x=><button key={x}>{x}</button>)}</div></section>
    <section className="vol panel"><h3>Controles de Volume</h3>{[['Frequência Original',master,setMaster],['Ruído Branco',white,setWhite],['Ruído Rosa',pink,setPink],['Ruído Marrom',brown,setBrown]].map(([n,v,set])=><label key={n}>{n} {v}%<input type="range" value={v} onChange={e=>set(+e.target.value)}/></label>)}</section>
    <section className="status panel"><h3>Status Global</h3><b>● PRONTO</b><p>Projeto novo • interface limpa</p></section>
   </section>
  </div>
 </main>
}
createRoot(document.getElementById('root')).render(<App/>);